# Generated by Django 5.0.1 on 2024-01-11 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Employee_Name', models.CharField(max_length=50)),
                ('Month', models.DateField(auto_now=True)),
                ('Item_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=50)),
                ('item_name', models.CharField(max_length=50)),
                ('item_measurement', models.CharField(choices=[('Nos', 'Nos'), ('Meter', 'Meter'), ('Kg', 'Kg'), ('Kilo meter', 'Kilo meter')], max_length=50)),
                ('item_quantity', models.IntegerField()),
                ('item_image', models.FileField(upload_to='Images')),
                ('supplier_name', models.CharField(max_length=50)),
                ('employee_name', models.CharField(max_length=50)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
