# Generated by Django 5.0.1 on 2024-01-11 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainUser', '0002_alter_employee_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_image',
            field=models.FileField(null=True, upload_to='Images'),
        ),
    ]
