# Generated by Django 5.0.1 on 2024-01-11 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainUser', '0003_alter_item_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_image',
            field=models.FileField(upload_to='Images'),
        ),
    ]
